// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV7BkBbt6ARJcxfXYEJ0y1s0T-qGNZaT0',
    appId: '1:301321629117:android:72b6ad18b362277cf376d4',
    messagingSenderId: '301321629117',
    projectId: 'my-finance-mate',
    storageBucket: 'my-finance-mate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfVgsZ0-xDGwsBUnD7qWsgCMqzW_ICDic',
    appId: '1:301321629117:ios:7a3349c0d82f26d5f376d4',
    messagingSenderId: '301321629117',
    projectId: 'my-finance-mate',
    storageBucket: 'my-finance-mate.appspot.com',
    androidClientId: '301321629117-16vs78ajniv94k4qv3s4mk7gg545adia.apps.googleusercontent.com',
    iosClientId: '301321629117-49v7numbttskobsd5689pmchj4mt6d9m.apps.googleusercontent.com',
    iosBundleId: 'com.mustafasyahmi.myfinancemate',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYt2T25d6tUcWCYuKTuDbo0tn80r7Cmu8',
    appId: '1:301321629117:web:67b7383f97617d73f376d4',
    messagingSenderId: '301321629117',
    projectId: 'my-finance-mate',
    authDomain: 'my-finance-mate.firebaseapp.com',
    storageBucket: 'my-finance-mate.appspot.com',
    measurementId: 'G-0RNBC8GB0T',
  );

}